In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

The importing data should be generated from the previous lecture(.ipynb file)

In [2]:
# Import training and validation sets (sorted)
df_tmp = pd.read_csv("../data/bluebook-for-bulldozers/TrainAndValid-after-01.csv",
                 low_memory=False,
                 parse_dates=["saledate"])

### Add datetime parameters for `saledate` column

In [3]:
df_tmp["saleYear"] = df_tmp.saledate.dt.year
df_tmp["saleMonth"] = df_tmp.saledate.dt.month
df_tmp["saleDay"] = df_tmp.saledate.dt.day
df_tmp["saleDayOfWeek"] = df_tmp.saledate.dt.dayofweek
df_tmp["saleDayOfYear"] = df_tmp.saledate.dt.dayofyear

In [4]:
df_tmp.head().T

,0,1,2,3,4
SalesID,1646770,1821514,1505138,1671174,1329056
SalePrice,9500.0,14000.0,50000.0,16000.0,22000.0
MachineID,1126363,1194089,1473654,1327630,1336053
ModelID,8434,10150,4139,8591,4089
datasource,132,132,132,132,132
auctioneerID,18.0,99.0,99.0,99.0,99.0
YearMade,1974,1980,1978,1980,1984
MachineHoursCurrentMeter,NaN,NaN,NaN,NaN,NaN
UsageBand,NaN,NaN,NaN,NaN,NaN
saledate,1989-01-17 00:00:00,1989-01-31 00:00:00,1989-01-31 00:00:00,1989-01-31 00:00:00,1989-01-31 00:00:00
fiModelDesc,TD20,A66,D7G,A62,D3B
fiBaseModel,TD20,A66,D7,A62,D3
fiSecondaryDesc,NaN,NaN,G,NaN,B
fiModelSeries,NaN,NaN,NaN,NaN,NaN
fiModelDescriptor,NaN,NaN,NaN,NaN,NaN
ProductSize,Medium,NaN,Large,NaN,NaN
fiProductClassDesc,"Track Type Tractor, Dozer - 105.0 to 130.0 Hor...",Wheel Loader - 120.0 to 135.0 Horsepower,"Track Type Tractor, Dozer - 190.0 to 260.0 Hor...",Wheel Loader - Unidentified,"Track Type Tractor, Dozer - 20.0 to 75.0 Horse..."
state,Texas,Florida,Florida,Florida,Florida
ProductGroup,TTT,WL,TTT,WL,TTT
ProductGroupDesc,Track Type Tractors,Wheel Loader,Track Type Tractors,Wheel Loader,Track Type Tractors
Drive_System,NaN,NaN,NaN,NaN,NaN
Enclosure,OROPS,OROPS,OROPS,EROPS,OROPS
Forks,NaN,None or Unspecified,NaN,None or Unspecified,NaN
Pad_Type,NaN,NaN,NaN,NaN,NaN
Ride_Control,NaN,None or Unspecified,NaN,None or Unspecified,NaN
Stick,NaN,NaN,NaN,NaN,NaN
Transmission,Direct Drive,NaN,Standard,NaN,Standard
Turbocharged,NaN,NaN,NaN,NaN,NaN
Blade_Extension,NaN,NaN,NaN,NaN,NaN
Blade_Width,NaN,NaN,NaN,NaN,NaN
Enclosure_Type,NaN,NaN,NaN,NaN,NaN
Engine_Horsepower,NaN,NaN,NaN,NaN,NaN
Hydraulics,2 Valve,2 Valve,2 Valve,2 Valve,2 Valve
Pushblock,NaN,NaN,NaN,NaN,NaN
Ripper,None or Unspecified,NaN,None or Unspecified,NaN,None or Unspecified
Scarifier,NaN,NaN,NaN,NaN,NaN
Tip_Control,NaN,NaN,NaN,NaN,NaN
Tire_Size,NaN,None or Unspecified,NaN,None or Unspecified,NaN
Coupler,NaN,None or Unspecified,NaN,None or Unspecified,NaN
Coupler_System,NaN,NaN,NaN,NaN,NaN
Grouser_Tracks,NaN,NaN,NaN,NaN,NaN
Hydraulics_Flow,NaN,NaN,NaN,NaN,NaN
Track_Type,NaN,NaN,NaN,NaN,NaN
Undercarriage_Pad_Width,NaN,NaN,NaN,NaN,NaN
Stick_Length,NaN,NaN,NaN,NaN,NaN
Thumb,NaN,NaN,NaN,NaN,NaN
Pattern_Changer,NaN,NaN,NaN,NaN,NaN
Grouser_Type,NaN,NaN,NaN,NaN,NaN
Backhoe_Mounting,None or Unspecified,NaN,None or Unspecified,NaN,None or Unspecified
Blade_Type,Straight,NaN,Straight,NaN,PAT
Travel_Controls,None or Unspecified,NaN,None or Unspecified,NaN,Lever
Differential_Type,NaN,Standard,NaN,Standard,NaN
Steering_Controls,NaN,Conventional,NaN,Conventional,NaN
saleYear,1989,1989,1989,1989,1989
saleMonth,1,1,1,1,1
saleDay,17,31,31,31,31
saleDayOfWeek,1,1,1,1,1
saleDayOfYear,17,31,31,31,31

In [5]:
# Now we've enriched our DataFrame with date time features, we can remove 'saledate'
df_tmp.drop("saledate", axis=1, inplace=True)

In [6]:
# Check the values of different columns
df_tmp.state.value_counts()

Florida           67320
Texas             53110
California        29761
Washington        16222
Georgia           14633
Maryland          13322
Mississippi       13240
Ohio              12369
Illinois          11540
Colorado          11529
New Jersey        11156
North Carolina    10636
Tennessee         10298
Alabama           10292
Pennsylvania      10234
South Carolina     9951
Arizona            9364
New York           8639
Connecticut        8276
Minnesota          7885
Missouri           7178
Nevada             6932
Louisiana          6627
Kentucky           5351
Maine              5096
Indiana            4124
Arkansas           3933
New Mexico         3631
Utah               3046
Unspecified        2801
Wisconsin          2745
New Hampshire      2738
Virginia           2353
Idaho              2025
Oregon             1911
Michigan           1831
Wyoming            1672
Montana            1336
Iowa               1336
Oklahoma           1326
Nebraska            866
West Virginia       840
Kansas              667
Delaware            510
North Dakota        480
Alaska              430
Massachusetts       347
Vermont             300
South Dakota        244
Hawaii              118
Rhode Island         83
Puerto Rico          42
Washington DC         2
Name: state, dtype: int64

In [7]:
df_tmp.head()

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,...,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,saleYear,saleMonth,saleDay,saleDayOfWeek,saleDayOfYear
0,1646770,9500.0,1126363,8434,132,18.0,1974,NaN,NaN,TD20,...,None or Unspecified,Straight,None or Unspecified,NaN,NaN,1989,1,17,1,17
1,1821514,14000.0,1194089,10150,132,99.0,1980,NaN,NaN,A66,...,NaN,NaN,NaN,Standard,Conventional,1989,1,31,1,31
2,1505138,50000.0,1473654,4139,132,99.0,1978,NaN,NaN,D7G,...,None or Unspecified,Straight,None or Unspecified,NaN,NaN,1989,1,31,1,31
3,1671174,16000.0,1327630,8591,132,99.0,1980,NaN,NaN,A62,...,NaN,NaN,NaN,Standard,Conventional,1989,1,31,1,31
4,1329056,22000.0,1336053,4089,132,99.0,1984,NaN,NaN,D3B,...,None or Unspecified,PAT,Lever,NaN,NaN,1989,1,31,1,31

In [8]:
len(df_tmp)

412698

## 5. Modelling 

We've done enough EDA (we could always do more) but let's start to do some model-driven EDA.

In [9]:
# Let's build a machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_jobs=-1,    #  -1 means using all processors
                              random_state=42)

X = df_tmp.drop("SalePrice", axis=1)
y = df_tmp["SalePrice"]

# model.fit(X, y)   # Error

In [10]:
# Export current tmp DataFrame
df_tmp.to_csv("../data/bluebook-for-bulldozers/TrainAndValid-after-02.csv", index=False)